baseURL: https://victoriametrics.com.cn/
languageCode: zh-CN
title: VictoriaMetrics 中文手册

module:
  imports:
  - path: github.com/imfing/hextra


params:
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/logo-victoriametrics.svg
      dark: images/logo-victoriametrics.svg
      link: /
      width: 40
      height: 20