baseURL: https://victoriametrics.com.cn/
languageCode: zh-cn
title: VicotiaMetrics 中文手册(WIP)

module:
  imports:
  - path: github.com/imfing/hextra

menu:
  main:
  - name: 手册
    pageRef: /docs
    weight: 1
  - name: 关于
    pageRef: /about
    weight: 2
  - name: 官方文档
    url: "https://docs.victoriametrics.com/"
    weight: 3
  - name: Search
    weight: 4
    params:
      type: search

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    style: github
  
enableRobotsTXT: true

params:
  description: "VictoriaMetrics 的中文文档手册，大部分内容翻译子官方文档；对文档内容进行了重新排版，更适合中国人的阅读习惯。仅保留了开源的内容，剔除了企业版相关内容。"
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: /logo-victoriametrics.svg
      dark: /logo-victoriametrics-dark.svg
      link: /
      width: 160
      height: 80
  search:
    enable: true
    type: flexsearch
    flexsearch:
      index: content
  highlight:
    copy:
      enable: true
      display: hover

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: wide

  comments:
    enable: false
    type: giscus
    giscus:
      repo: victoriametrics-docs
      repoId: R_kgDOM4cSJQ
      category: General
      categoryId: DIC_kwDOM4cSJc4Ci4Hu
  footer:
    displayCopyright: true
    displayPoweredBy: false
  theme:
    default: system
    displayToggle: true

defaultContentLanguage: zh-cn